eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  instance:
    hostname: localhost
    
microservice:
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/api/order/orders/
  product-service:
    endpoints:
      endpoint:
        uri: http://PRODUCT-SERVICE/api/product/products
  customer-service:
    endpoints:
      endpoint:
        uri: http://CUSTOMER-SERVICE/api/customer/customers
