eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
microservice:
  order-service:
    endpoints:
      endpoint:
        uri: http://GATEWAY-SERVICE/api/order/orders
  product-service:
    endpoints:
      endpoint:
        uri: http://GATEWAY-SERVICE/api/product/products
  customer-service:
    endpoints:
      endpoint:
        uri: http://GATEWAY-SERVICE/api/customer/customers
